name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn

      - name: Patch expo/cli for linux
        run: yarn patch-package

      - name: Setup example
        run: yarn setup

      - name: Run tests
        run: yarn test
